In [30]:
import numpy as np
c = np.arange(6)
print("array is\n",c)

array is
 [0 1 2 3 4 5]


In [31]:
import numpy as np
a=np.random.randint(10,20,6)
print("array is\n",a)

array is
 [17 17 11 12 17 14]


In [32]:
import numpy as np
arr=np.random.random((3,3,3))
print("random values in array:\n",arr)

random values in array:
 [[[0.11349967 0.31417288 0.88139254]
  [0.35415376 0.24578415 0.15059059]
  [0.95103754 0.13138525 0.9586792 ]]

 [[0.24562071 0.59728597 0.33693754]
  [0.39257021 0.35610927 0.02443414]
  [0.61971579 0.66558105 0.50257284]]

 [[0.68547877 0.82271345 0.94941035]
  [0.41358142 0.15259775 0.80698362]
  [0.44456131 0.42626148 0.56836064]]]


In [11]:
import numpy as np
arr=np.random.random((5,5))
print(arr)
print("Min element:",arr.min())
print("Max element:",arr.max())

[[0.92765465 0.09000429 0.77082905 0.28205168 0.74080809]
 [0.7959674  0.50700638 0.50164131 0.56037278 0.0911476 ]
 [0.22255268 0.94264574 0.00693875 0.22556371 0.17058963]
 [0.86990996 0.52098399 0.36949868 0.67722265 0.01101766]
 [0.23928003 0.71289042 0.46217465 0.83000195 0.52629005]]
Min element: 0.006938752808073212
Max element: 0.9426457424117027


In [14]:
import numpy as np
arr=np.random.random((10,4))
print(arr)
print("---------------------------------------------")
a=arr[0:5,0:4]
print(a)

[[0.43093198 0.69848981 0.69891272 0.44258464]
 [0.79551145 0.70517268 0.637196   0.53398706]
 [0.9302024  0.92164218 0.39428097 0.32043289]
 [0.81016413 0.35786655 0.54352947 0.01250926]
 [0.04038578 0.42024545 0.0046837  0.0784449 ]
 [0.14397146 0.58419387 0.95866479 0.12592857]
 [0.60714642 0.14169598 0.98665337 0.7125739 ]
 [0.50121774 0.81163102 0.5309236  0.09663327]
 [0.6151652  0.72624572 0.03239068 0.30000117]
 [0.59389741 0.15963352 0.6523136  0.39259918]]
---------------------------------------------
[[0.43093198 0.69848981 0.69891272 0.44258464]
 [0.79551145 0.70517268 0.637196   0.53398706]
 [0.9302024  0.92164218 0.39428097 0.32043289]
 [0.81016413 0.35786655 0.54352947 0.01250926]
 [0.04038578 0.42024545 0.0046837  0.0784449 ]]


In [17]:
import numpy as np
arr=np.arange((10))
print(arr)
print("--------------------------------------")
a=np.random.shuffle(arr)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
--------------------------------------
[4 7 0 8 1 5 2 9 6 3]


In [19]:
import numpy as np
a=np.random.random((2,2))
print(a)
print("-----------------------------------")
b=np.random.random((2,2))
print(b)
print("--------------------------")
c=np.array_equal(a,b)
if c==False:
    print("Not equal.....")
    
else:
    print("Equal....")



[[0.38486282 0.869601  ]
 [0.72440638 0.74647521]]
-----------------------------------
[[0.40572831 0.10328687]
 [0.98339489 0.85352753]]
--------------------------
Not equal.....


In [38]:
import numpy as np
arr=np.random.random((15))
print("First matrix is:\n",arr)
print("-------------------------------------")
arr[arr.argmax()]=-1
print("New matrix:\n",arr)

First matrix is:
 [0.95421125 0.89691121 0.79350077 0.05664002 0.12393853 0.1538225
 0.87060426 0.62600922 0.12896808 0.63160752 0.72631612 0.31113456
 0.17011591 0.92083734 0.1239022 ]
-------------------------------------
New matrix:
 [-1.          0.89691121  0.79350077  0.05664002  0.12393853  0.1538225
  0.87060426  0.62600922  0.12896808  0.63160752  0.72631612  0.31113456
  0.17011591  0.92083734  0.1239022 ]


In [29]:
import numpy as np
arr=np.random.randint(0,10,9)
print(arr)

print("Frequent value in array:\n",np.bincount(arr).argmax() )

[0 5 6 4 6 9 3 5 7]
Frequent value in array:
 5
