In [32]:
import numpy as np
arr=np.genfromtxt("result.txt",skip_header=1,filling_values=999)
print(arr)
print("--------------------------------------------")
a=arr[0:1,1:4].sum()
print("Marks of 111 student:",a)
b=arr[1:2,1:4].sum()
print("Marks of 112 student:",b)

c=arr[2:3,1:4].sum()
print("Marks of 113 student:",c)

d=arr[3:4,1:4].sum()
print("Marks of 114 student:",d)

e=arr[4:5,1:4].sum()
print("Marks of 115 student",e)

if a>b and a>c and a>d and a>e:
    print("111 has highest marks:")
elif b>c and b>d and b>e:
    print("112 has highest marks:")
elif c>d and c>e:
    print("113 has highest marks:")
elif c>e:
    print("114 has highest marks:")
else:
    print("115 has highest marks:")

print("--------------------------------------------")
if a<150:
    print("111 is failed.....")
elif b<150:
    print("112 is failed.....")
elif c<150:
    print("113 is failed......")
elif d<150:
    print("114 is failed......")
else:
    print("115 is failed......")
print("-------------------------------------------")    
#Subjectwise topper
English=arr[0:5,1:2].max()
print("Highest marks in English:\n",English)
Maths=arr[0:5,2:3].max()
print("Highest marks in Maths:\n",Maths)
Science=arr[0:5,3:4].max()
print("Highest marks in Science:\n",Science)

#Subjectwise fails
eng=arr[0:5,1:2]
print("Fail in English:\n",eng[eng<40])
math=arr[0:5,2:3]
print("Fail in maths:\n",math[math<40])
sci=arr[0:5,3:4]
print("Fail in science:\n",sci[sci<40])

[[111.  80.  90.  77.]
 [112.  81.  58.  60.]
 [113.  34.  52.  54.]
 [114.  89.  40.  27.]
 [115.  75.  82.  36.]]
--------------------------------------------
Marks of 111 student: 247.0
Marks of 112 student: 199.0
Marks of 113 student: 140.0
Marks of 114 student: 156.0
Marks of 115 student 193.0
111 has highest marks:
--------------------------------------------
113 is failed......
-------------------------------------------
Highest marks in English:
 89.0
Highest marks in Maths:
 90.0
Highest marks in Science:
 77.0
Fail in English:
 [34.]
Fail in maths:
 []
Fail in science:
 [27. 36.]
